# Generated by Django 3.2.4 on 2021-06-12 05:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('making_time', models.CharField(max_length=100, verbose_name='調理時間')),
                ('serves', models.CharField(max_length=100, verbose_name='人前')),
                ('ingredients', models.CharField(max_length=300, verbose_name='材料')),
                ('cost', models.IntegerField(verbose_name='値段')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='最終更新日時')),
            ],
        ),
    ]
